// <auto-generated />
using System;
using EcommerceBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceBackend.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    partial class EcommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EcommerceBackend.Data.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShippingEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ShippingFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ShippingState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShippingZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8283),
                            Description = "Premium noise-canceling wireless headphones with 30-hour battery life.",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
                            Name = "Wireless Headphones",
                            Price = 199.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8293),
                            Description = "Feature-rich smartwatch with health tracking and GPS.",
                            ImageUrl = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
                            Name = "Smart Watch",
                            Price = 299.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8296),
                            Description = "Ergonomic aluminum laptop stand for better posture.",
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
                            Name = "Laptop Stand",
                            Price = 49.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8298),
                            Description = "RGB mechanical gaming keyboard with Cherry MX switches.",
                            ImageUrl = "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400",
                            Name = "Mechanical Keyboard",
                            Price = 129.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 5,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8299),
                            Description = "7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader.",
                            ImageUrl = "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400",
                            Name = "USB-C Hub",
                            Price = 39.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8301),
                            Description = "Ergonomic wireless mouse with precision tracking.",
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
                            Name = "Wireless Mouse",
                            Price = 59.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 7,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8303),
                            Description = "Adjustable monitor stand with storage drawer.",
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
                            Name = "Monitor Stand",
                            Price = 79.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8305),
                            Description = "1080p HD webcam with built-in microphone.",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b91a603?w=400",
                            Name = "Webcam HD",
                            Price = 89.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 9,
                            Category = "Home",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8306),
                            Description = "LED desk lamp with adjustable brightness and color temperature.",
                            ImageUrl = "https://images.unsplash.com/photo-1507440658841-9a2dd3a70d17?w=400",
                            Name = "Desk Lamp",
                            Price = 44.99m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 10,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8308),
                            Description = "Portable Bluetooth speaker with 360-degree sound.",
                            ImageUrl = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400",
                            Name = "Bluetooth Speaker",
                            Price = 79.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 11,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8310),
                            Description = "Adjustable phone stand for desk.",
                            ImageUrl = "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400",
                            Name = "Phone Stand",
                            Price = 19.99m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 12,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 3, 11, 12, 10, 30, 833, DateTimeKind.Utc).AddTicks(8312),
                            Description = "Desktop cable management system.",
                            ImageUrl = "https://images.unsplash.com/photo-1558002038-1091a1661116?w=400",
                            Name = "Cable Organizer",
                            Price = 24.99m,
                            Stock = 90
                        });
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.CartItem", b =>
                {
                    b.HasOne("EcommerceBackend.Data.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Data.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.Order", b =>
                {
                    b.HasOne("EcommerceBackend.Data.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("EcommerceBackend.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Data.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.WishlistItem", b =>
                {
                    b.HasOne("EcommerceBackend.Data.Entities.Product", "Product")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Data.Entities.User", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("EcommerceBackend.Data.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
